version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://localhost:29092,CONTROLLER://localhost:9093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.122.1
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4318:4318"
      - "4317:4317"
    volumes:
      - ./otel-collector.yml:/etc/otelcol/config.yaml:ro
    depends_on:
      - tempo
      - loki
      - mimir

  tempo:
    image: grafana/tempo:2.8.0
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"
      - "4319:4317"
    volumes:
      - ./tempo.yml:/etc/tempo.yaml:ro

  loki:
    image: grafana/loki:3.4.1
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki/local-config.yaml:ro

  mimir:
    image: grafana/mimir:latest
    command:
      - "-config.file=/etc/mimir/demo.yaml"
    ports:
      - "9009:9009"
    volumes:
      - ./mimir.yml:/etc/mimir/demo.yaml:ro

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    depends_on:
      - tempo
      - loki
      - mimir