multitenancy_enabled: false

server:
  http_listen_port: 9009
  log_level: info

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/tsdb

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/blocks
  tsdb:
    dir: /data/tsdb

compactor:
  data_dir: /data/compactor

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  ring:
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/rules

store_gateway:
  sharding_ring:
    replication_factor: 1